{{ config(materialized='table') }}

WITH
    CUSTOMERS AS (
        SELECT CUSTOMER_ID, CUSTOMER_NAME
        FROM SF_DBT_LANDING.RETAIL_CSV_DATA.CUSTOMERS
    ),

    PRODUCTS AS (SELECT * FROM SF_DBT_LANDING.RETAIL_CSV_DATA.PRODUCTS),

    ADDRESSES AS (SELECT * FROM SF_DBT_LANDING.RETAIL_CSV_DATA.ADDRESSES),

    ORDERS AS (
        SELECT ORDER_ID as ID, CUSTOMER_ID, PRODUCT_ID, ADDRESS_ID, SALES
        FROM SF_DBT_LANDING.RETAIL_CSV_DATA.ORDERS
    )

SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    P.PRODUCT,
    A.CITY,
    A.COUNTRY,
    SUM(SALES) AS TOTAL_SALES,
    COUNT(1) AS TIMES_ORDERED
FROM ADDRESSES A
INNER JOIN ORDERS O ON A.ADDRESS_ID = O.ADDRESS_ID
INNER JOIN CUSTOMERS C ON C.CUSTOMER_ID = O.CUSTOMER_ID
INNER JOIN PRODUCTS P ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY C.CUSTOMER_ID, C.CUSTOMER_NAME, P.PRODUCT, A.CITY, A.COUNTRY
HAVING COUNT(1) > 1
